<?php

module_load_include('inc', 'agent_point', 'includes/AgentPointAPI');

/**
 * Implements hook_menu().
 */

function agent_point_menu() {
  $items = array();

  $items['admin/config/services/agent_point_settings'] = array(
    'title' => 'Agent Point Settings',
    'description' => 'Configuration for Agent Point',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('agent_point_settings_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/** configuration form for the Agent Point API Service */

function agent_point_settings_form($form, &$form_state) {
  $form['description'] = array(
    '#type' => 'item',
    '#title' => t('Agent Point Configuration Form'),
  );

  $form['settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Retail and Agency Types'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
//    '#tree' =>TRUE
  );
  
  $form['settings']['agency_types'] = array(
    '#type' => 'checkboxes',
    '#options' => drupal_map_assoc(array(t('CGA'), t('MAA'), t('Retail Centers'))),
    '#title' => t('Select Retail and Agency Types'),
    '#default_value' => variable_get('agency_types'),
  );
    

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}



function agent_point_settings_form_submit($form, &$form_state) {
  $agency_types = array_keys(array_flip($form_state['values']['agency_types']));
  $ap = new AgentPointAPI($agency_types);
  $ap->connect();
  variable_set('agency_types', $agency_types); 
}